databases:
  - module: cdn-keys
    filename: cloud_keys.yml
    download-urls:
      - https://github.com/winezer0/cdnAnalyzer/blob/main/assets/cloud_keys.yml
    keep-updated: false
    enable: true

  - module: cdn-domains
    filename: cdn.yml
    download-urls:
      - https://github.com/winezer0/cdnAnalyzer/blob/main/assets/cdn.yml
    keep-updated: false
    enable: true

  - module: cdn-sources-china
    filename: sources_china.json
    download-urls:
      - https://github.com/hanbufei/isCdn/blob/main/client/data/sources_china.json
#      - https://github.com/winezer0/cdnAnalyzer/blob/main/assets/sources_china.json
    keep-updated: false
    enable: true

  - module: cdn-sources-foreign
    filename: sources_foreign.json
    download-urls:
      - https://github.com/projectdiscovery/cdncheck/blob/main/sources_data.json
    keep-updated: true
    enable: true

  - module: cdn-provider-foreign
    filename: provider_foreign.yaml
    download-urls:
      - https://github.com/projectdiscovery/cdncheck/blob/main/cmd/generate-index/provider.yaml
    keep-updated: false
    enable: true

  - module: unknown-cdn-cname
    filename: unknown-cdn-cname.txt
    download-urls:
      - https://github.com/alwaystest18/cdnChecker/blob/master/cdn_cname
    keep-updated: false
    enable: true

  - module: cdn-sources-china2
    filename: sources_china2.json
    download-urls:
      - https://github.com/mabangde/cdncheck_cn/blob/main/sources_data.json
    keep-updated: false
    enable: true