databases:
  - module: cdn-keys
    filename: cloud_keys.yml
    download-urls:
      - https://github.com/winezer0/cdnAnalyzer/blob/main/assets/cloud_keys.yml
    keep-updated: false
    enable: false

  - module: cdn-domains
    filename: cdn.yml
    download-urls:
      - https://github.com/winezer0/cdnAnalyzer/blob/main/assets/cdn.yml
    keep-updated: false
    enable: false

  - module: cdn-sources-china
    filename: sources_china.json
    download-urls:
      - https://github.com/hanbufei/isCdn/blob/main/client/data/sources_china.json
#      - https://github.com/winezer0/cdnAnalyzer/blob/main/assets/sources_china.json
    keep-updated: false
    enable: false

  - module: cdn-sources-foreign
    filename: sources_foreign.json
    download-urls:
      - https://github.com/projectdiscovery/cdncheck/blob/main/sources_data.json
    keep-updated: true
    enable: false
