# 基本参数
# DNS并发和超时设置
dns-timeout: 5
resolvers-num: 5
city-map-num: 5
dns-concurrency: 8
edns-concurrency: 8
query-edns-cnames: true
query-edns-use-sys-ns: false

# 数据库路径配置
download-items:
  - module: qqwry
    filename: qqwry.dat
    download-urls:
      - https://github.com/metowolf/qqwry.dat/releases/latest/download/qqwry.dat
    keep-updated: true

  - module: zxipv6wry
    filename: zxipv6wry.db
    download-urls:
      - https://github.com/winezer0/cdnAnalyzer/blob/main/assets/zxipv6wry.db
    keep-updated: false

  - module: geolite2-asn-ipv4
    filename: geolite2-asn-ipv4.mmdb
    download-urls:
      - https://github.com/sapics/ip-location-db/blob/main/geolite2-asn-mmdb/geolite2-asn-ipv4.mmdb
    keep-updated: true

  - module: geolite2-asn-ipv6
    filename: geolite2-asn-ipv6.mmdb
    download-urls:
      - https://github.com/sapics/ip-location-db/blob/main/geolite2-asn-mmdb/geolite2-asn-ipv6.mmdb
    keep-updated: true

  - module: cdn
    filename: cdn.yml
    download-urls:
      - https://raw.githubusercontent.com/4ft35t/cdn/master/src/cdn.yml
      - https://cdn.jsdelivr.net/gh/4ft35t/cdn/src/cdn.yml
    keep-updated: false

  - module: dns-resolvers
    filename: resolvers.txt
    download-urls:
      - https://github.com/winezer0/cdnAnalyzer/blob/main/assets/resolvers.txt
    keep-updated: false

  - module: edns-city-ip
    filename: city_ip.csv
    download-urls:
      - https://github.com/winezer0/cdnAnalyzer/blob/main/assets/city_ip.csv
    keep-updated: false

  - module: cdn-keys
    filename: cloud_keys.yml
    download-urls:
      - https://github.com/winezer0/cdnAnalyzer/blob/main/assets/cloud_keys.yml
    keep-updated: false

  - module: cdn-sources_china
    filename: sources_china.json
    download-urls:
      - https://github.com/hanbufei/isCdn/blob/main/client/data/sources_china.json
    keep-updated: false

  - module: cdn-sources-foreign
    filename: sources_foreign.json
    download-urls:
      - https://github.com/projectdiscovery/cdncheck/blob/main/sources_data.json
    keep-updated: true

  - module: cdn-sources
    filename: sources.json
    download-urls:
      - https://github.com/winezer0/cdnAnalyzer/blob/main/assets/source.json
    keep-updated: true
