# 基本参数
# DNS并发和超时设置
dns-timeout: 5
resolvers-num: 5
city-map-num: 5
dns-concurrency: 8
edns-concurrency: 8
query-edns-cnames: true
query-edns-use-sys-ns: false

# 数据库路径配置
download-items:
  - module: qqwry
    filename: qqwry.dat
    download-urls:
      - https://github.com/metowolf/qqwry.dat/releases/latest/download/qqwry.dat
      - https://github.com/winezer0/cdnAnalyzer/blob/main/assets/qqwry.dat
    keep-updated: true
    enable: true

  - module: zxipv6wry
    filename: zxipv6wry.db
    download-urls:
      - https://github.com/winezer0/cdnAnalyzer/blob/main/assets/zxipv6wry.db
      - https://raw.githubusercontent.com/ZX-Inc/zxipdb-python/main/data/ipv6wry.db
      - https://cdn.jsdelivr.net/gh/winezer0/cdnAnalyzer/assets/zxipv6wry.db
    keep-updated: false
    enable: true

  - module: geolite2-asn
    filename: geolite2-asn.mmdb
    download-urls:
      - https://github.com/sapics/ip-location-db/blob/main/geolite2-asn-mmdb/geolite2-asn.mmdb
      - https://github.com/winezer0/cdnAnalyzer/blob/main/assets/geolite2-asn.mmdb
      - https://cdn.jsdelivr.net/gh/winezer0/cdnAnalyzer/assets/geolite2-asn.mmdb
    keep-updated: true
    enable: true

  - module: dns-resolvers
    filename: resolvers.txt
    download-urls:
      - https://github.com/winezer0/cdnAnalyzer/blob/main/assets/resolvers.txt
      - https://cdn.jsdelivr.net/gh/winezer0/cdnAnalyzer/assets/resolvers.txt
    keep-updated: false
    enable: true

  - module: edns-city-ip
    filename: city_ip.csv
    download-urls:
      - https://github.com/winezer0/cdnAnalyzer/blob/main/assets/city_ip.csv
      - https://cdn.jsdelivr.net/gh/winezer0/cdnAnalyzer/assets/city_ip.csv
    keep-updated: false
    enable: true

  - module: cdn-sources
    filename: sources.json
    download-urls:
      - https://github.com/winezer0/cdnAnalyzer/blob/main/assets/sources.json
      - https://cdn.jsdelivr.net/gh/winezer0/cdnAnalyzer/assets/sources.json
    keep-updated: true
    enable: true

  - module: ip2region_v4
    filename: ip2region_v4.xdb
    download-urls:
      - https://github.com/lionsoul2014/ip2region/blob/master/data/ip2region_v4.xdb
    keep-updated: true
    enable: false

  - module: ip2region_v6
    filename: ip2region_v6.xdb
    download-urls:
      - https://github.com/lionsoul2014/ip2region/blob/master/data/ip2region_v6.xdb
    keep-updated: false
    enable: false